services:
  nginx-server:
    build:
      context: ./nginx
    image: cse644-haproxy-nginx:1.0
    container_name: cse644-nginx-backend
    networks:
      - proxy-network

  haproxy:
    build:
      context: ./haproxy
    image: cse644-haproxy:1.0
    container_name: cse644-haproxy
    ports:
      - "8090:80"
    depends_on:
      - nginx-server
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge