FROM nginx:alpine

LABEL maintainer="Rod Raemon Alvero"
LABEL course="CSE644 Advanced Cloud Computing"
LABEL description="Customized Nginx image for Docker Assignment"

COPY index.html /usr/share/nginx/html/index.html

EXPOSE 80