apiVersion: v1
kind: ConfigMap

metadata:
  name: python-config
  namespace: cse644

data:
  PUBLIC_MESSAGE: "GitOps change successfully reconciled by Argo CD."
  APP_ENVIRONMENT: "Docker Desktop Kubernetes - Argo CD Managed"