apiVersion: v1
kind: Service

metadata:
  name: python-web-service
  namespace: cse644

spec:
  type: ClusterIP

  selector:
    app: python-web

  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888