apiVersion: v1
kind: ConfigMap

metadata:
  name: python-config
  namespace: cse644

data:
  PUBLIC_MESSAGE: "Configuration updated successfully using ConfigMap."
  APP_ENVIRONMENT: "Docker Desktop Kubernetes"